wandb_version: 1

run:
  desc: null
  value:
    log: true
    project_name: mpg_hmm_test
    run_tag: null
    n_episodes: 1000
    update_rate: 100
    smf_dist: 0.005
    hmm_conf: configs/hmm_default.yaml
    mpg_conf: configs/mpg_default.yaml
    seed: null
hmm:
  desc: null
  value:
    cells_per_column: 10
    lr: 0.1
    batch_size: 100
    initialization: dirichlet
    alpha: 1.0
mpg:
  desc: null
  value:
    transition_probs:
    - - 0
      - 1
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - - 0
      - 0
      - 0.5
      - 0.5
      - 0
      - 0
      - 0
      - 0
    - - 0
      - 0
      - 0.5
      - 0
      - 0
      - 0.5
      - 0
      - 0
    - - 0
      - 0
      - 0
      - 0.5
      - 0.5
      - 0
      - 0
      - 0
    - - 0
      - 0
      - 0.5
      - 0
      - 0
      - 0
      - 0.5
      - 0
    - - 0
      - 0
      - 0
      - 0
      - 0.5
      - 0
      - 0.5
      - 0
    - - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 1
    - - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    transition_letters:
    - - 0
      - B
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    - - 0
      - 0
      - P
      - T
      - 0
      - 0
      - 0
      - 0
    - - 0
      - 0
      - T
      - 0
      - 0
      - V
      - 0
      - 0
    - - 0
      - 0
      - 0
      - S
      - X
      - 0
      - 0
      - 0
    - - 0
      - 0
      - X
      - 0
      - 0
      - 0
      - S
      - 0
    - - 0
      - 0
      - 0
      - 0
      - P
      - 0
      - V
      - 0
    - - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - E
    - - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    alphabet:
    - B
    - P
    - T
    - V
    - S
    - X
    - E
    initial_state: 0
    autoreset: false
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.15.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689861555.404705
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.15.5
      8:
      - 5
